package com.mulesoft.workshop.servicedesk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-10-05T16:44:43.606-04:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IAccountsService")
@XmlSeeAlso({ObjectFactory.class})
public interface IAccountsService {

    @WebResult(name = "createEmailResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAccountsService/createEmail", output = "http://tempuri.org/IAccountsService/createEmailResponse")
    @RequestWrapper(localName = "createEmail", targetNamespace = "http://tempuri.org/", className = "com.mulesoft.workshop.servicedesk.CreateEmail")
    @WebMethod(action = "http://tempuri.org/IAccountsService/createEmail")
    @ResponseWrapper(localName = "createEmailResponse", targetNamespace = "http://tempuri.org/", className = "com.mulesoft.workshop.servicedesk.CreateEmailResponse")
    public java.lang.String createEmail(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.mulesoft.workshop.servicedesk.CreateRequest request
    );

    @WebResult(name = "createAccountResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAccountsService/createAccount", output = "http://tempuri.org/IAccountsService/createAccountResponse")
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://tempuri.org/", className = "com.mulesoft.workshop.servicedesk.CreateAccount")
    @WebMethod(action = "http://tempuri.org/IAccountsService/createAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://tempuri.org/", className = "com.mulesoft.workshop.servicedesk.CreateAccountResponse")
    public com.mulesoft.workshop.servicedesk.AccountDetails createAccount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.mulesoft.workshop.servicedesk.CreateRequest request
    );

    @WebResult(name = "findAccountByAccountNameResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAccountsService/findAccountByAccountName", output = "http://tempuri.org/IAccountsService/findAccountByAccountNameResponse")
    @RequestWrapper(localName = "findAccountByAccountName", targetNamespace = "http://tempuri.org/", className = "com.mulesoft.workshop.servicedesk.FindAccountByAccountName")
    @WebMethod(action = "http://tempuri.org/IAccountsService/findAccountByAccountName")
    @ResponseWrapper(localName = "findAccountByAccountNameResponse", targetNamespace = "http://tempuri.org/", className = "com.mulesoft.workshop.servicedesk.FindAccountByAccountNameResponse")
    public com.mulesoft.workshop.servicedesk.AccountDetails findAccountByAccountName(
        @WebParam(name = "accountName", targetNamespace = "http://tempuri.org/")
        java.lang.String accountName
    );
}
