
package com.mulesoft.workshop.servicedesk;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-10-05T16:44:43.587-04:00
 * Generated source version: 2.5.1
 * 
 */
public final class IAccountsService_BasicHttpBindingIAccountsService_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "AccountsService");

    private IAccountsService_BasicHttpBindingIAccountsService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AccountsService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AccountsService ss = new AccountsService(wsdlURL, SERVICE_NAME);
        IAccountsService port = ss.getBasicHttpBindingIAccountsService();  
        
        {
        System.out.println("Invoking createEmail...");
        com.mulesoft.workshop.servicedesk.CreateRequest _createEmail_request = null;
        java.lang.String _createEmail__return = port.createEmail(_createEmail_request);
        System.out.println("createEmail.result=" + _createEmail__return);


        }
        {
        System.out.println("Invoking createAccount...");
        com.mulesoft.workshop.servicedesk.CreateRequest _createAccount_request = null;
        com.mulesoft.workshop.servicedesk.AccountDetails _createAccount__return = port.createAccount(_createAccount_request);
        System.out.println("createAccount.result=" + _createAccount__return);


        }
        {
        System.out.println("Invoking findAccountByAccountName...");
        java.lang.String _findAccountByAccountName_accountName = "";
        com.mulesoft.workshop.servicedesk.AccountDetails _findAccountByAccountName__return = port.findAccountByAccountName(_findAccountByAccountName_accountName);
        System.out.println("findAccountByAccountName.result=" + _findAccountByAccountName__return);


        }

        System.exit(0);
    }

}
