package com.mulesoft.workshop.servicedesk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-10-05T16:44:43.617-04:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "AccountsService", 
                  wsdlLocation = "http://localhost/ServiceDesk/AccountsService.svc?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class AccountsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "AccountsService");
    public final static QName BasicHttpBindingIAccountsService = new QName("http://tempuri.org/", "BasicHttpBinding_IAccountsService");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/ServiceDesk/AccountsService.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AccountsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost/ServiceDesk/AccountsService.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AccountsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AccountsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IAccountsService
     */
    @WebEndpoint(name = "BasicHttpBinding_IAccountsService")
    public IAccountsService getBasicHttpBindingIAccountsService() {
        return super.getPort(BasicHttpBindingIAccountsService, IAccountsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAccountsService
     */
    @WebEndpoint(name = "BasicHttpBinding_IAccountsService")
    public IAccountsService getBasicHttpBindingIAccountsService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIAccountsService, IAccountsService.class, features);
    }

}
